version: "3.1"

services:
  database:
    image: mariadb:latest
    restart: always
    container_name: database
    ports:
      - "3306:3306"
    env_file:
      - "./mariadb.env"
    volumes:
      - mariadb-volume:/var/lib/mysql:rw
      - ./database/mariadb.sql:/docker-entrypoint-initdb.d/01_mariadb.sql:ro
      - ./database/file_mariadb.sql:/docker-entrypoint-initdb.d/02_files.sql:ro
      - ./database/dummy_mariadb.sql:/docker-entrypoint-initdb.d/03_dummy.sql:ro
    networks:
      - mariadb-network
    hostname: mariadb-database

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - "9980:8080"
    networks:
      - mariadb-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb-database
    depends_on:
      - database
    networks:
      - mariadb-network
    ports:
      - 9880:80

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    restart: always
    ports:
      - 8880:8080
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - API_URL=swagger.yaml
    volumes:
      - ./api.yaml:/usr/share/nginx/html/swagger.yaml
    restart: always
    ports:
      - 8881:8080

networks:
  mariadb-network:
    driver: bridge

volumes:
  mariadb-volume:
