version: "3.9"

services:
  alive-db:
    image: mariadb:latest
    restart: always
    container_name: alive-db
    volumes:
      - mariadb-volume:/var/lib/mysql:rw
      - ./backend/database/alive.sql:/docker-entrypoint-initdb.d/01_alive.sql:ro
    env_file:
      - ./.env
    networks:
      - alive-network
    hostname: mariadb-database
  backend:
    build: ./backend
    image: alive-backend
    restart: always
    container_name: alive-backend
    depends_on:
      - alive-db
    environment:
      - MYSQL_HOST=mariadb-database
    env_file:
      - ./.env
    networks:
      - alive-network
    hostname: alive-backend
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: alive-phpmyadmin
    environment:
      - PMA_HOST=mariadb-database
      - UPLOAD_LIMIT=900M
    depends_on:
      - alive-db
    networks:
      - alive-network
    hostname: alive-phpmyadmin
  frontend:
    build: ./frontend/phaser
    image: alive-frontend
    restart: always
    container_name: alive-frontend
    hostname: alive-frontend
    environment:
      - NGINX_PORT=80
    depends_on:
      - backend
    networks:
      - alive-network
    ports:
      - 8081:80

networks:
  alive-network:

volumes:
  mariadb-volume:
