version: "3.9"

services:
  database:
    image: mariadb:latest
    restart: always
    container_name: database
    volumes:
      - mariadb-volume:/var/lib/mysql:rw
      - ./database/alive.sql:/docker-entrypoint-initdb.d/01_alive.sql:ro
    env_file:
      - ./.env
    networks:
      - mariadb-network
    hostname: mariadb-database
  backend:
    build: .
    image: alive-backend
    restart: always
    container_name: alive-backend
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      - mariadb-network
    ports:
      - 8080:8080
    hostname: alive-backend
networks:
  mariadb-network:

volumes:
  mariadb-volume:
